export const NATIONALITY_COOKIE = 'nationality'
export const NATIONALITY_COOKIE_MAX_AGE = 60 * 60 * 24 * 365 // 1 year

// All countries — sorted alphabetically by English name
export const NATIONALITIES = [
  { iso2: 'AF', flag: '🇦🇫', en: 'Afghanistan', ar: 'أفغانستان' },
  { iso2: 'AL', flag: '🇦🇱', en: 'Albania', ar: 'ألبانيا' },
  { iso2: 'DZ', flag: '🇩🇿', en: 'Algeria', ar: 'الجزائر' },
  { iso2: 'AD', flag: '🇦🇩', en: 'Andorra', ar: 'أندورا' },
  { iso2: 'AO', flag: '🇦🇴', en: 'Angola', ar: 'أنغولا' },
  { iso2: 'AG', flag: '🇦🇬', en: 'Antigua & Barbuda', ar: 'أنتيغوا وبربودا' },
  { iso2: 'AR', flag: '🇦🇷', en: 'Argentina', ar: 'الأرجنتين' },
  { iso2: 'AM', flag: '🇦🇲', en: 'Armenia', ar: 'أرمينيا' },
  { iso2: 'AU', flag: '🇦🇺', en: 'Australia', ar: 'أستراليا' },
  { iso2: 'AT', flag: '🇦🇹', en: 'Austria', ar: 'النمسا' },
  { iso2: 'AZ', flag: '🇦🇿', en: 'Azerbaijan', ar: 'أذربيجان' },
  { iso2: 'BS', flag: '🇧🇸', en: 'Bahamas', ar: 'جزر البهاما' },
  { iso2: 'BH', flag: '🇧🇭', en: 'Bahrain', ar: 'البحرين' },
  { iso2: 'BD', flag: '🇧🇩', en: 'Bangladesh', ar: 'بنغلاديش' },
  { iso2: 'BB', flag: '🇧🇧', en: 'Barbados', ar: 'بربادوس' },
  { iso2: 'BY', flag: '🇧🇾', en: 'Belarus', ar: 'بيلاروسيا' },
  { iso2: 'BE', flag: '🇧🇪', en: 'Belgium', ar: 'بلجيكا' },
  { iso2: 'BZ', flag: '🇧🇿', en: 'Belize', ar: 'بليز' },
  { iso2: 'BJ', flag: '🇧🇯', en: 'Benin', ar: 'بنين' },
  { iso2: 'BT', flag: '🇧🇹', en: 'Bhutan', ar: 'بوتان' },
  { iso2: 'BO', flag: '🇧🇴', en: 'Bolivia', ar: 'بوليفيا' },
  { iso2: 'BA', flag: '🇧🇦', en: 'Bosnia & Herzegovina', ar: 'البوسنة والهرسك' },
  { iso2: 'BW', flag: '🇧🇼', en: 'Botswana', ar: 'بوتسوانا' },
  { iso2: 'BR', flag: '🇧🇷', en: 'Brazil', ar: 'البرازيل' },
  { iso2: 'BN', flag: '🇧🇳', en: 'Brunei', ar: 'بروناي' },
  { iso2: 'BG', flag: '🇧🇬', en: 'Bulgaria', ar: 'بلغاريا' },
  { iso2: 'BF', flag: '🇧🇫', en: 'Burkina Faso', ar: 'بوركينا فاسو' },
  { iso2: 'BI', flag: '🇧🇮', en: 'Burundi', ar: 'بوروندي' },
  { iso2: 'CV', flag: '🇨🇻', en: 'Cabo Verde', ar: 'الرأس الأخضر' },
  { iso2: 'KH', flag: '🇰🇭', en: 'Cambodia', ar: 'كمبوديا' },
  { iso2: 'CM', flag: '🇨🇲', en: 'Cameroon', ar: 'الكاميرون' },
  { iso2: 'CA', flag: '🇨🇦', en: 'Canada', ar: 'كندا' },
  { iso2: 'CF', flag: '🇨🇫', en: 'Central African Republic', ar: 'جمهورية أفريقيا الوسطى' },
  { iso2: 'TD', flag: '🇹🇩', en: 'Chad', ar: 'تشاد' },
  { iso2: 'CL', flag: '🇨🇱', en: 'Chile', ar: 'تشيلي' },
  { iso2: 'CN', flag: '🇨🇳', en: 'China', ar: 'الصين' },
  { iso2: 'CO', flag: '🇨🇴', en: 'Colombia', ar: 'كولومبيا' },
  { iso2: 'KM', flag: '🇰🇲', en: 'Comoros', ar: 'جزر القمر' },
  { iso2: 'CG', flag: '🇨🇬', en: 'Congo', ar: 'الكونغو' },
  { iso2: 'CD', flag: '🇨🇩', en: 'Congo (DRC)', ar: 'الكونغو الديمقراطية' },
  { iso2: 'CR', flag: '🇨🇷', en: 'Costa Rica', ar: 'كوستاريكا' },
  { iso2: 'HR', flag: '🇭🇷', en: 'Croatia', ar: 'كرواتيا' },
  { iso2: 'CU', flag: '🇨🇺', en: 'Cuba', ar: 'كوبا' },
  { iso2: 'CY', flag: '🇨🇾', en: 'Cyprus', ar: 'قبرص' },
  { iso2: 'CZ', flag: '🇨🇿', en: 'Czech Republic', ar: 'التشيك' },
  { iso2: 'DK', flag: '🇩🇰', en: 'Denmark', ar: 'الدنمارك' },
  { iso2: 'DJ', flag: '🇩🇯', en: 'Djibouti', ar: 'جيبوتي' },
  { iso2: 'DM', flag: '🇩🇲', en: 'Dominica', ar: 'دومينيكا' },
  { iso2: 'DO', flag: '🇩🇴', en: 'Dominican Republic', ar: 'جمهورية الدومينيكان' },
  { iso2: 'EC', flag: '🇪🇨', en: 'Ecuador', ar: 'الإكوادور' },
  { iso2: 'EG', flag: '🇪🇬', en: 'Egypt', ar: 'مصر' },
  { iso2: 'SV', flag: '🇸🇻', en: 'El Salvador', ar: 'السلفادور' },
  { iso2: 'GQ', flag: '🇬🇶', en: 'Equatorial Guinea', ar: 'غينيا الاستوائية' },
  { iso2: 'ER', flag: '🇪🇷', en: 'Eritrea', ar: 'إريتريا' },
  { iso2: 'EE', flag: '🇪🇪', en: 'Estonia', ar: 'إستونيا' },
  { iso2: 'SZ', flag: '🇸🇿', en: 'Eswatini', ar: 'إسواتيني' },
  { iso2: 'ET', flag: '🇪🇹', en: 'Ethiopia', ar: 'إثيوبيا' },
  { iso2: 'FJ', flag: '🇫🇯', en: 'Fiji', ar: 'فيجي' },
  { iso2: 'FI', flag: '🇫🇮', en: 'Finland', ar: 'فنلندا' },
  { iso2: 'FR', flag: '🇫🇷', en: 'France', ar: 'فرنسا' },
  { iso2: 'GA', flag: '🇬🇦', en: 'Gabon', ar: 'الغابون' },
  { iso2: 'GM', flag: '🇬🇲', en: 'Gambia', ar: 'غامبيا' },
  { iso2: 'GE', flag: '🇬🇪', en: 'Georgia', ar: 'جورجيا' },
  { iso2: 'DE', flag: '🇩🇪', en: 'Germany', ar: 'ألمانيا' },
  { iso2: 'GH', flag: '🇬🇭', en: 'Ghana', ar: 'غانا' },
  { iso2: 'GR', flag: '🇬🇷', en: 'Greece', ar: 'اليونان' },
  { iso2: 'GD', flag: '🇬🇩', en: 'Grenada', ar: 'غرينادا' },
  { iso2: 'GT', flag: '🇬🇹', en: 'Guatemala', ar: 'غواتيمالا' },
  { iso2: 'GN', flag: '🇬🇳', en: 'Guinea', ar: 'غينيا' },
  { iso2: 'GW', flag: '🇬🇼', en: 'Guinea-Bissau', ar: 'غينيا بيساو' },
  { iso2: 'GY', flag: '🇬🇾', en: 'Guyana', ar: 'غيانا' },
  { iso2: 'HT', flag: '🇭🇹', en: 'Haiti', ar: 'هايتي' },
  { iso2: 'HN', flag: '🇭🇳', en: 'Honduras', ar: 'هندوراس' },
  { iso2: 'HU', flag: '🇭🇺', en: 'Hungary', ar: 'المجر' },
  { iso2: 'IS', flag: '🇮🇸', en: 'Iceland', ar: 'آيسلندا' },
  { iso2: 'IN', flag: '🇮🇳', en: 'India', ar: 'الهند' },
  { iso2: 'ID', flag: '🇮🇩', en: 'Indonesia', ar: 'إندونيسيا' },
  { iso2: 'IR', flag: '🇮🇷', en: 'Iran', ar: 'إيران' },
  { iso2: 'IQ', flag: '🇮🇶', en: 'Iraq', ar: 'العراق' },
  { iso2: 'IE', flag: '🇮🇪', en: 'Ireland', ar: 'أيرلندا' },
  { iso2: 'IL', flag: '🇮🇱', en: 'Israel', ar: 'إسرائيل' },
  { iso2: 'IT', flag: '🇮🇹', en: 'Italy', ar: 'إيطاليا' },
  { iso2: 'CI', flag: '🇨🇮', en: 'Ivory Coast', ar: 'ساحل العاج' },
  { iso2: 'JM', flag: '🇯🇲', en: 'Jamaica', ar: 'جامايكا' },
  { iso2: 'JP', flag: '🇯🇵', en: 'Japan', ar: 'اليابان' },
  { iso2: 'JO', flag: '🇯🇴', en: 'Jordan', ar: 'الأردن' },
  { iso2: 'KZ', flag: '🇰🇿', en: 'Kazakhstan', ar: 'كازاخستان' },
  { iso2: 'KE', flag: '🇰🇪', en: 'Kenya', ar: 'كينيا' },
  { iso2: 'KI', flag: '🇰🇮', en: 'Kiribati', ar: 'كيريباتي' },
  { iso2: 'KW', flag: '🇰🇼', en: 'Kuwait', ar: 'الكويت' },
  { iso2: 'KG', flag: '🇰🇬', en: 'Kyrgyzstan', ar: 'قيرغيزستان' },
  { iso2: 'LA', flag: '🇱🇦', en: 'Laos', ar: 'لاوس' },
  { iso2: 'LV', flag: '🇱🇻', en: 'Latvia', ar: 'لاتفيا' },
  { iso2: 'LB', flag: '🇱🇧', en: 'Lebanon', ar: 'لبنان' },
  { iso2: 'LS', flag: '🇱🇸', en: 'Lesotho', ar: 'ليسوتو' },
  { iso2: 'LR', flag: '🇱🇷', en: 'Liberia', ar: 'ليبيريا' },
  { iso2: 'LY', flag: '🇱🇾', en: 'Libya', ar: 'ليبيا' },
  { iso2: 'LI', flag: '🇱🇮', en: 'Liechtenstein', ar: 'ليختنشتاين' },
  { iso2: 'LT', flag: '🇱🇹', en: 'Lithuania', ar: 'ليتوانيا' },
  { iso2: 'LU', flag: '🇱🇺', en: 'Luxembourg', ar: 'لوكسمبورغ' },
  { iso2: 'MG', flag: '🇲🇬', en: 'Madagascar', ar: 'مدغشقر' },
  { iso2: 'MW', flag: '🇲🇼', en: 'Malawi', ar: 'مالاوي' },
  { iso2: 'MY', flag: '🇲🇾', en: 'Malaysia', ar: 'ماليزيا' },
  { iso2: 'MV', flag: '🇲🇻', en: 'Maldives', ar: 'جزر المالديف' },
  { iso2: 'ML', flag: '🇲🇱', en: 'Mali', ar: 'مالي' },
  { iso2: 'MT', flag: '🇲🇹', en: 'Malta', ar: 'مالطا' },
  { iso2: 'MH', flag: '🇲🇭', en: 'Marshall Islands', ar: 'جزر مارشال' },
  { iso2: 'MR', flag: '🇲🇷', en: 'Mauritania', ar: 'موريتانيا' },
  { iso2: 'MU', flag: '🇲🇺', en: 'Mauritius', ar: 'موريشيوس' },
  { iso2: 'MX', flag: '🇲🇽', en: 'Mexico', ar: 'المكسيك' },
  { iso2: 'FM', flag: '🇫🇲', en: 'Micronesia', ar: 'ميكرونيزيا' },
  { iso2: 'MD', flag: '🇲🇩', en: 'Moldova', ar: 'مولدوفا' },
  { iso2: 'MC', flag: '🇲🇨', en: 'Monaco', ar: 'موناكو' },
  { iso2: 'MN', flag: '🇲🇳', en: 'Mongolia', ar: 'منغوليا' },
  { iso2: 'ME', flag: '🇲🇪', en: 'Montenegro', ar: 'الجبل الأسود' },
  { iso2: 'MA', flag: '🇲🇦', en: 'Morocco', ar: 'المغرب' },
  { iso2: 'MZ', flag: '🇲🇿', en: 'Mozambique', ar: 'موزمبيق' },
  { iso2: 'MM', flag: '🇲🇲', en: 'Myanmar', ar: 'ميانمار' },
  { iso2: 'NA', flag: '🇳🇦', en: 'Namibia', ar: 'ناميبيا' },
  { iso2: 'NR', flag: '🇳🇷', en: 'Nauru', ar: 'ناورو' },
  { iso2: 'NP', flag: '🇳🇵', en: 'Nepal', ar: 'نيبال' },
  { iso2: 'NL', flag: '🇳🇱', en: 'Netherlands', ar: 'هولندا' },
  { iso2: 'NZ', flag: '🇳🇿', en: 'New Zealand', ar: 'نيوزيلندا' },
  { iso2: 'NI', flag: '🇳🇮', en: 'Nicaragua', ar: 'نيكاراغوا' },
  { iso2: 'NE', flag: '🇳🇪', en: 'Niger', ar: 'النيجر' },
  { iso2: 'NG', flag: '🇳🇬', en: 'Nigeria', ar: 'نيجيريا' },
  { iso2: 'KP', flag: '🇰🇵', en: 'North Korea', ar: 'كوريا الشمالية' },
  { iso2: 'MK', flag: '🇲🇰', en: 'North Macedonia', ar: 'مقدونيا الشمالية' },
  { iso2: 'NO', flag: '🇳🇴', en: 'Norway', ar: 'النرويج' },
  { iso2: 'OM', flag: '🇴🇲', en: 'Oman', ar: 'عُمان' },
  { iso2: 'PK', flag: '🇵🇰', en: 'Pakistan', ar: 'باكستان' },
  { iso2: 'PW', flag: '🇵🇼', en: 'Palau', ar: 'بالاو' },
  { iso2: 'PS', flag: '🇵🇸', en: 'Palestine', ar: 'فلسطين' },
  { iso2: 'PA', flag: '🇵🇦', en: 'Panama', ar: 'بنما' },
  { iso2: 'PG', flag: '🇵🇬', en: 'Papua New Guinea', ar: 'بابوا غينيا الجديدة' },
  { iso2: 'PY', flag: '🇵🇾', en: 'Paraguay', ar: 'باراغواي' },
  { iso2: 'PE', flag: '🇵🇪', en: 'Peru', ar: 'بيرو' },
  { iso2: 'PH', flag: '🇵🇭', en: 'Philippines', ar: 'الفلبين' },
  { iso2: 'PL', flag: '🇵🇱', en: 'Poland', ar: 'بولندا' },
  { iso2: 'PT', flag: '🇵🇹', en: 'Portugal', ar: 'البرتغال' },
  { iso2: 'QA', flag: '🇶🇦', en: 'Qatar', ar: 'قطر' },
  { iso2: 'RO', flag: '🇷🇴', en: 'Romania', ar: 'رومانيا' },
  { iso2: 'RU', flag: '🇷🇺', en: 'Russia', ar: 'روسيا' },
  { iso2: 'RW', flag: '🇷🇼', en: 'Rwanda', ar: 'رواندا' },
  { iso2: 'KN', flag: '🇰🇳', en: 'Saint Kitts & Nevis', ar: 'سانت كيتس ونيفيس' },
  { iso2: 'LC', flag: '🇱🇨', en: 'Saint Lucia', ar: 'سانت لوسيا' },
  { iso2: 'VC', flag: '🇻🇨', en: 'Saint Vincent & Grenadines', ar: 'سانت فنسنت وجزر غرينادين' },
  { iso2: 'WS', flag: '🇼🇸', en: 'Samoa', ar: 'ساموا' },
  { iso2: 'SM', flag: '🇸🇲', en: 'San Marino', ar: 'سان مارينو' },
  { iso2: 'ST', flag: '🇸🇹', en: 'São Tomé & Príncipe', ar: 'ساو تومي وبرينسيبي' },
  { iso2: 'SA', flag: '🇸🇦', en: 'Saudi Arabia', ar: 'السعودية' },
  { iso2: 'SN', flag: '🇸🇳', en: 'Senegal', ar: 'السنغال' },
  { iso2: 'RS', flag: '🇷🇸', en: 'Serbia', ar: 'صربيا' },
  { iso2: 'SC', flag: '🇸🇨', en: 'Seychelles', ar: 'سيشيل' },
  { iso2: 'SL', flag: '🇸🇱', en: 'Sierra Leone', ar: 'سيراليون' },
  { iso2: 'SG', flag: '🇸🇬', en: 'Singapore', ar: 'سنغافورة' },
  { iso2: 'SK', flag: '🇸🇰', en: 'Slovakia', ar: 'سلوفاكيا' },
  { iso2: 'SI', flag: '🇸🇮', en: 'Slovenia', ar: 'سلوفينيا' },
  { iso2: 'SB', flag: '🇸🇧', en: 'Solomon Islands', ar: 'جزر سليمان' },
  { iso2: 'SO', flag: '🇸🇴', en: 'Somalia', ar: 'الصومال' },
  { iso2: 'ZA', flag: '🇿🇦', en: 'South Africa', ar: 'جنوب أفريقيا' },
  { iso2: 'KR', flag: '🇰🇷', en: 'South Korea', ar: 'كوريا الجنوبية' },
  { iso2: 'SS', flag: '🇸🇸', en: 'South Sudan', ar: 'جنوب السودان' },
  { iso2: 'ES', flag: '🇪🇸', en: 'Spain', ar: 'إسبانيا' },
  { iso2: 'LK', flag: '🇱🇰', en: 'Sri Lanka', ar: 'سريلانكا' },
  { iso2: 'SD', flag: '🇸🇩', en: 'Sudan', ar: 'السودان' },
  { iso2: 'SR', flag: '🇸🇷', en: 'Suriname', ar: 'سورينام' },
  { iso2: 'SE', flag: '🇸🇪', en: 'Sweden', ar: 'السويد' },
  { iso2: 'CH', flag: '🇨🇭', en: 'Switzerland', ar: 'سويسرا' },
  { iso2: 'SY', flag: '🇸🇾', en: 'Syria', ar: 'سوريا' },
  { iso2: 'TW', flag: '🇹🇼', en: 'Taiwan', ar: 'تايوان' },
  { iso2: 'TJ', flag: '🇹🇯', en: 'Tajikistan', ar: 'طاجيكستان' },
  { iso2: 'TZ', flag: '🇹🇿', en: 'Tanzania', ar: 'تنزانيا' },
  { iso2: 'TH', flag: '🇹🇭', en: 'Thailand', ar: 'تايلاند' },
  { iso2: 'TL', flag: '🇹🇱', en: 'Timor-Leste', ar: 'تيمور الشرقية' },
  { iso2: 'TG', flag: '🇹🇬', en: 'Togo', ar: 'توغو' },
  { iso2: 'TO', flag: '🇹🇴', en: 'Tonga', ar: 'تونغا' },
  { iso2: 'TT', flag: '🇹🇹', en: 'Trinidad & Tobago', ar: 'ترينيداد وتوباغو' },
  { iso2: 'TN', flag: '🇹🇳', en: 'Tunisia', ar: 'تونس' },
  { iso2: 'TR', flag: '🇹🇷', en: 'Turkey', ar: 'تركيا' },
  { iso2: 'TM', flag: '🇹🇲', en: 'Turkmenistan', ar: 'تركمانستان' },
  { iso2: 'TV', flag: '🇹🇻', en: 'Tuvalu', ar: 'توفالو' },
  { iso2: 'UG', flag: '🇺🇬', en: 'Uganda', ar: 'أوغندا' },
  { iso2: 'UA', flag: '🇺🇦', en: 'Ukraine', ar: 'أوكرانيا' },
  { iso2: 'AE', flag: '🇦🇪', en: 'United Arab Emirates', ar: 'الإمارات' },
  { iso2: 'GB', flag: '🇬🇧', en: 'United Kingdom', ar: 'المملكة المتحدة' },
  { iso2: 'US', flag: '🇺🇸', en: 'United States', ar: 'الولايات المتحدة' },
  { iso2: 'UY', flag: '🇺🇾', en: 'Uruguay', ar: 'أوروغواي' },
  { iso2: 'UZ', flag: '🇺🇿', en: 'Uzbekistan', ar: 'أوزبكستان' },
  { iso2: 'VU', flag: '🇻🇺', en: 'Vanuatu', ar: 'فانواتو' },
  { iso2: 'VE', flag: '🇻🇪', en: 'Venezuela', ar: 'فنزويلا' },
  { iso2: 'VN', flag: '🇻🇳', en: 'Vietnam', ar: 'فيتنام' },
  { iso2: 'YE', flag: '🇾🇪', en: 'Yemen', ar: 'اليمن' },
  { iso2: 'ZM', flag: '🇿🇲', en: 'Zambia', ar: 'زامبيا' },
  { iso2: 'ZW', flag: '🇿🇼', en: 'Zimbabwe', ar: 'زيمبابوي' },
] as const

export type NationalityIso2 = typeof NATIONALITIES[number]['iso2']

export function getNationality(iso2: string) {
  return NATIONALITIES.find((n) => n.iso2 === iso2) ?? null
}

export function nationalityLabel(iso2: string, locale: string): string {
  const n = getNationality(iso2)
  if (!n) return iso2
  return locale === 'ar' ? n.ar : n.en
}
